export const initialFacilities = [
  {
    id: 1,
    name: "Main Restrooms",
    type: "restroom",
    location: "Main Entrance",
    status: "operational",
    features: ["Wheelchair accessible", "Baby changing", "Family restroom"],
    lastMaintenance: "2023-05-15",
    description: "Large restroom facility with multiple stalls and amenities.",
  },
  {
    id: 2,
    name: "Safari Zone Restrooms",
    type: "restroom",
    location: "Safari Zone",
    status: "operational",
    features: ["Wheelchair accessible", "Baby changing"],
    lastMaintenance: "2023-05-10",
    description: "Medium-sized restroom facility serving the Safari Zone area.",
  },
  {
    id: 3,
    name: "Visitor Center",
    type: "information",
    location: "Main Plaza",
    status: "operational",
    features: [
      "Information desk",
      "Lost and found",
      "Tour booking",
      "Gift shop",
    ],
    lastMaintenance: "2023-04-30",
    description: "Central information hub for visitors with various services.",
  },
  {
    id: 4,
    name: "Rainforest Rest Area",
    type: "rest_area",
    location: "Rainforest Zone",
    status: "maintenance",
    features: ["Seating", "Shade", "Water fountains"],
    lastMaintenance: "2023-05-20",
    description:
      "Covered seating area for visitors to rest in the Rainforest Zone.",
  },
  {
    id: 5,
    name: "North Gate Storage",
    type: "storage",
    location: "North Gate",
    status: "operational",
    features: ["Equipment storage", "Staff only"],
    lastMaintenance: "2023-05-12",
    description: "Storage facility for maintenance and cleaning equipment.",
  },
  {
    id: 6,
    name: "Children's Playground",
    type: "rest_area",
    location: "Kids Zone",
    status: "operational",
    features: ["Playground", "Seating", "Shade"],
    lastMaintenance: "2023-05-18",
    description: "Playground area with benches and shade for families.",
  },
  {
    id: 7,
    name: "Aquarium Info Desk",
    type: "information",
    location: "Aquarium Entrance",
    status: "operational",
    features: ["Information desk", "Guided tour info"],
    lastMaintenance: "2023-05-08",
    description: "Information desk for aquarium visitors and tour bookings.",
  },
  {
    id: 8,
    name: "East Restrooms",
    type: "restroom",
    location: "East Wing",
    status: "maintenance",
    features: ["Wheelchair accessible"],
    lastMaintenance: "2023-05-22",
    description: "Restroom facility currently under maintenance.",
  },
  {
    id: 9,
    name: "Picnic Area",
    type: "rest_area",
    location: "Lake Side",
    status: "operational",
    features: ["Picnic tables", "Trash bins", "Shade"],
    lastMaintenance: "2023-05-14",
    description: "Outdoor picnic area with tables and shade near the lake.",
  },
  {
    id: 10,
    name: "Lost & Found",
    type: "information",
    location: "Main Entrance",
    status: "operational",
    features: ["Lost and found", "Information desk"],
    lastMaintenance: "2023-05-11",
    description: "Lost and found office for visitor belongings.",
  },
  {
    id: 11,
    name: "Staff Break Room",
    type: "other",
    location: "Admin Building",
    status: "operational",
    features: ["Seating", "Kitchenette", "Rest area"],
    lastMaintenance: "2023-05-09",
    description: "Break room for zoo staff with basic amenities.",
  },
  {
    id: 12,
    name: "Butterfly Garden Rest Area",
    type: "rest_area",
    location: "Butterfly Garden",
    status: "operational",
    features: ["Seating", "Shade", "Water fountains"],
    lastMaintenance: "2023-05-13",
    description: "Rest area for visitors in the Butterfly Garden.",
  },
  {
    id: 13,
    name: "West Storage",
    type: "storage",
    location: "West Wing",
    status: "closed",
    features: ["Equipment storage"],
    lastMaintenance: "2023-04-28",
    description: "Storage facility currently closed for renovations.",
  },
  {
    id: 14,
    name: "Giraffe Overlook Restrooms",
    type: "restroom",
    location: "Giraffe Overlook",
    status: "operational",
    features: ["Wheelchair accessible", "Family restroom"],
    lastMaintenance: "2023-05-16",
    description: "Restroom facility near the Giraffe Overlook.",
  },
];

export const initialFirstAid = [
  {
    id: 1,
    name: "Main First Aid Station",
    location: "Visitor Center",
    status: "operational",
    staffed: true,
    staffingHours: "9:00 AM - 6:00 PM",
    equipment: ["AED", "First aid kits", "Wheelchair", "Stretcher"],
    description: "Primary first aid station with trained medical staff.",
  },
  {
    id: 2,
    name: "Safari Zone Medical Point",
    location: "Safari Zone",
    status: "operational",
    staffed: true,
    staffingHours: "10:00 AM - 5:00 PM",
    equipment: ["First aid kits", "AED"],
    description: "Satellite first aid station for the Safari Zone area.",
  },
  {
    id: 3,
    name: "Aquatic Zone First Aid",
    location: "Aquatic Zone",
    status: "unstaffed",
    staffed: false,
    staffingHours: "N/A",
    equipment: ["First aid kits", "Emergency phone"],
    description: "Unstaffed first aid cabinet with emergency communication.",
  },
];

export type SafetyItem = {
  id: number;
  name: string;
  type: string;
  locations: string[];
  status: string;
  description: string;
  lastInspection?: string;
};

// Sample data for safety features
export const initialSafety: SafetyItem[] = [
  {
    id: 1,
    name: "Emergency Evacuation Plan",
    type: "evacuation",
    locations: ["All zones"],
    lastInspection: "2023-04-01",
    status: "active",
    description:
      "Comprehensive evacuation plan with marked routes throughout the zoo.",
  },
  {
    id: 2,
    name: "Animal Escape Protocol",
    type: "protocol",
    locations: ["All animal enclosures"],
    lastInspection: "2023-03-10",
    status: "active",
    description: "Procedures for handling animal escapes and visitor safety.",
  },
  {
    id: 3,
    name: "Weather Emergency Plan",
    type: "protocol",
    locations: ["All zones"],
    lastInspection: "2023-02-15",
    status: "active",
    description:
      "Procedures for severe weather events including shelter locations.",
  },
  {
    id: 4,
    name: "Fire Suppression System",
    type: "evacuation",
    locations: ["All buildings"],
    lastInspection: "2023-01-15",
    status: "active",
    description:
      "Automatic sprinkler and alarm systems in all enclosed structures.",
  },
];
